
import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,

  SignedOut,

} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "../components/ui/button"
import Providers from "../components/Providers";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" data-qb-installed="true" suppressHydrationWarning>
    <ClerkProvider>
      <Providers>
   
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* {isHome && (
              <header className="header p-4 flex gap-2">
                <SignedOut>
                  <Button variant="default" asChild>
                    <SignInButton />
                  </Button>
                  <Button variant="default" asChild>
                    <SignUpButton />
                  </Button>
                </SignedOut>
              </header>
            )} */}
          {children}
          <Toaster></Toaster>
        </body>

      </Providers>
    </ClerkProvider>
      </html>
  );
}
